# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_VoiceCommandList.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InformationVoice(object):
    def setupUi(self, InformationVoice):
        InformationVoice.setObjectName("InformationVoice")
        InformationVoice.resize(261, 490)
        self.verticalLayoutWidget = QtWidgets.QWidget(InformationVoice)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 261, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setEnabled(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(InformationVoice)
        QtCore.QMetaObject.connectSlotsByName(InformationVoice)

    def retranslateUi(self, InformationVoice):
        _translate = QtCore.QCoreApplication.translate
        InformationVoice.setWindowTitle(_translate("InformationVoice", "Information Voice"))
        self.label_13.setText(_translate("InformationVoice", "Lista de comandos de voz"))
        self.label_2.setText(_translate("InformationVoice", "Reproduce:\"Nombre de canción o video\""))
        self.label_4.setText(_translate("InformationVoice", "Hora:(Da la hora actual)"))
        self.label_3.setText(_translate("InformationVoice", "Quién es:\"Nombre de la persona\" "))
        self.label_6.setText(_translate("InformationVoice", "Busca:(nombre de la busqueda en google)"))
        self.label_9.setText(_translate("InformationVoice", "Chiste:(Cuenta un chiste)"))
        self.label_10.setText(_translate("InformationVoice", "Qué es:\"Nombre del objeto o cosa\""))
        self.label_8.setText(_translate("InformationVoice", "Abre:{Facebook,twitter,reddit,cuevana o google}"))
        self.label_12.setText(_translate("InformationVoice", "Que paso en:\'Nombre del sitio o acontecimiento\'"))
        self.label_11.setText(_translate("InformationVoice", "Llamame: \'Nombre actual\'"))
        self.label_7.setText(_translate("InformationVoice", "Dime mi nombre:(Menciona el nombre de la persona)"))
        self.label_5.setText(_translate("InformationVoice", "Cómo estás:(Menciona el estado del asistente)"))
        self.label.setText(_translate("InformationVoice", "Apágate:(Cierra el programa)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InformationVoice = QtWidgets.QWidget()
    ui = Ui_InformationVoice()
    ui.setupUi(InformationVoice)
    InformationVoice.show()
    sys.exit(app.exec_())
